# Generated by Django 4.1.4 on 2022-12-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Контент'),
        ),
    ]
