# Generated by Django 4.1.4 on 2022-12-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_responses_accepted_alter_notice_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категории'),
        ),
    ]
