# Generated by Django 4.1.4 on 2022-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_category_name_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='accepted',
            field=models.BooleanField(),
        ),
    ]
