# Generated by Django 4.1.4 on 2022-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_responses_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='author_names',
            field=models.ManyToManyField(to='project.author'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='accepted',
            field=models.BooleanField(default=None, verbose_name='Принято/Отклонено'),
        ),
    ]
